# Generated by Django 3.0.8 on 2021-02-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_Staff',
            new_name='is_staff',
        ),
    ]
